version: "3.4"

services:

  webui:
    container_name: 'demo_webui'
    image: 'demo_webui'
    #restart: always
    build:
      context: ./../
      dockerfile: ./infra/webui-dockerfile
    ports:
      - 5500:80
    depends_on:
      - webapi

  webapi:
    container_name: 'demo_webapi'
    image: 'demo_webapi'
    #restart: always
    build:
      context: ./../
      dockerfile: ./infra/webapi-dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
      - DefaultTimeZone=Europe/Amsterdam
      - DefaultCulture=nl-NL
      - WebApiBaseUrl=http://demo:80
      - Auth0__Domain=https://dev-spke9m2i.us.auth0.com/
      - Auth0__Audience=https://demo
      - Auth0__RedirectUrl=http://localhost:5500
      - Auth0__Management__ClientId=uRAKIp1D24jeOktYy9JGtLz5mnjMLb17
      - Auth0__Management__ClientSecret=${AUTH0_MANAGEMENT_CLIENTSECRET}
      - Auth0__Management__UserDatabaseIdentifier=Username-Password-Authentication
      - Postgres__ConnectionString=Server=postgres;Port=5432;Database=Demo;User Id=demo;Password=P@ssw0rd!;
      - RabbitMq__Host=rabbitmq:5672
      - RabbitMq__Username=demo
      - RabbitMq__Password=P@ssw0rd!
      - Redis__Host=redis
      - Redis__Port=6379
      - Redis__Password=P4ssw0rd!
      - ElasticSearch__Uri=http://elasticsearch:9200
      - ElasticSearch__Username=elastic
      - ElasticSearch__Password=P@ssw0rd!
      - Email__Host=mailhog
      - Email__Port=1025
      - Email__FromAddress=noreply@demo.com
      - Email__Username=
      - Email__Password=
    ports:
      - 5501:80
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    container_name: 'demo_postgres'
    image: postgres:14.1-alpine
    #restart: always
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=P@ssw0rd!
    ports:
      - 5502:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      
  rabbitmq:
    container_name: 'demo_rabbitmq'
    image: rabbitmq:3-management-alpine
    #restart: always
    ports:
      - 5503:5672
      - 5504:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log_data:/var/log/rabbitmq
    environment:
      - DEFAULT_USER=demo
      - DEFAULT_PASS=P@ssw0rd!
            
  redis:
    container_name: 'demo_redis'
    image: redis:alpine3.16
    #restart: always
    ports:
      - 5505:6379
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=P4ssw0rd!

  redis-commander:
    container_name: 'demo_redis_commander'
    image: rediscommander/redis-commander:latest
    #restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=P4ssw0rd!
      - HTTP_USER=demo
      - HTTP_PASSWORD=P@ssw0rd!
    ports:
      - 5506:8081

  elasticsearch:
    container_name: 'demo_elasticsearch'
    image: elasticsearch:7.9.2
    #restart: always
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=P@ssw0rd!
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=true
      - discovery.type=single-node
    ports:
      - 5507:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: 'demo_kibana'
    image: kibana:7.9.2
    #restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=P@ssw0rd!
      - XPACK_SECURITY_ENABLED=true
    ports:
      - 5508:5601
    depends_on:
      - elasticsearch

  mailhog:
    container_name: 'demo_mailhog'
    image: mailhog/mailhog:latest
    #restart: always
    ports:
      - 5509:1025
      - 5510:8025

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log_data:
  redis_data:
  elasticsearch_data: