@baseUrl = https://localhost:44309


# @name get
GET {{baseUrl}}/api/applicationsettings
Accept: application/json

###

# @name update
PUT {{baseUrl}}/api/applicationsettings
Content-Type: application/json

{
  "settings": {
    "setting1": true,
    "setting2": "test3",
    "setting3": "2021-01-01T00:00:00Z",
    "setting4": "986ce6ee-90c9-406d-9161-a329d3f65d91",
    "setting5": 10.5
  },
  "timestamp": "AAAAAAABAeI="
}

###

# @name auditlog
GET {{baseUrl}}/api/applicationsettings/auditlog
  ?pageIndex=0
  &pageSize=10
Accept: application/json

###
