@baseUrl = https://localhost:5001
@access_token = {{ auth.response.body.$.access_token}}

# @name auth
POST https://dev-spke9m2i.us.auth0.com/oauth/token
Content-Type: application/json

{ 
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "audience": "{{audience}}",
  "grant_type": "client_credentials"
}

###

# @name get
GET {{baseUrl}}/api/currentuser
Accept: application/json
Authorization: Bearer {{access_token}}

###

# @name update
PUT {{baseUrl}}/api/currentuser
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "givenName": "string",
  "middleName": "string",
  "familyName": "string"
}

###

# @name auditlog
GET {{baseUrl}}/api/applicationsettings/auditlog
  ?pageIndex=0
  &pageSize=10
Accept: application/json
Authorization: Bearer {{access_token}}

###
