@baseUrl = https://localhost:5001
@access_token = {{ auth.response.body.$.access_token}}
@createdCustomerLocation = {{create.response.headers.location}}

# @name auth
POST https://dev-spke9m2i.us.auth0.com/oauth/token
Content-Type: application/json

{ 
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "audience": "{{audience}}",
  "grant_type": "client_credentials"
}

###

# @name search
GET {{baseUrl}}/api/customers
  ?orderBy=0 
  &orderByDescending=true
  &pageIndex=0
  &pageSize=10
Accept: application/json
Authorization: Bearer {{access_token}}

###

# @name create
POST {{baseUrl}}/api/customers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Test"
}

###

# @name getById
GET {{createdCustomerLocation}}
Accept: application/json
Authorization: Bearer {{access_token}}

###

# @name update
PUT {{createdCustomerLocation}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "xmin": 0,
  "name": "Test3"
}

###

# @name auditlog
GET {{createdCustomerLocation}}/auditlog
  ?pageIndex=0
  &pageSize=10
Accept: application/json
Authorization: Bearer {{access_token}}

###

# @name delete
DELETE {{createdCustomerLocation}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
}

###

# @name lookup
GET {{baseUrl}}/api/customers/lookup
  ?orderBy=0 
  &orderByDescending=true
  &pageIndex=0
  &pageSize=10
  //&searchTerm=Microsoft
  //&ids=E8ACA2F3-2BBF-45AD-7F16-08D9F7A0C34A
  //&ids=7B27EE10-6D87-4C49-7F14-08D9F7A0C34A
Accept: application/json
Authorization: Bearer {{access_token}}

###