@baseUrl = https://localhost:5001
@access_token = {{ auth.response.body.$.access_token}}

# @name auth
POST https://dev-spke9m2i.us.auth0.com/oauth/token
Content-Type: application/json

{ 
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "audience": "{{audience}}",
  "grant_type": "client_credentials"
}

###

# @name get
GET {{baseUrl}}/api/FeatureFlagSettings
Accept: application/json
Authorization: Bearer {{access_token}}

###

# @name update
PUT {{baseUrl}}/api/FeatureFlagSettings
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "settings": {
    "featureFlags": [
      {
        "name": "Test",
        "description": "Test",
        "enabledForAll": true,
        "enabledForUsers": [],
        "id": "bed3b6fa-6a09-4389-a9ab-73a5c698d111",
        "xmin": 0,
      }
    ]
  },
  "xmin": 0
}

###

# @name auditlog
GET {{baseUrl}}/api/FeatureFlagSettings/auditlog
  ?pageIndex=0
  &pageSize=10
Accept: application/json
Authorization: Bearer {{access_token}}

###
