@baseUrl = https://localhost:44309
@createdInvoiceLocation = {{create.response.headers.location}}
@copyInvoiceLocation = {{copy.response.headers.location}}
#@createdInvoiceId = {{create.response.body.$.id}}

# @name search
GET {{baseUrl}}/api/invoices
  ?orderBy=0 
  &orderByDescending=true
  &pageIndex=0
  &pageSize=10
Accept: application/json

###

# @name create
POST {{baseUrl}}/api/invoices
Content-Type: application/json

{
  "customerId": "2d9d9aae-6c8c-447f-9861-08d9042c6bca",
  "invoiceDate": "2021-04-24T00:00:00",
  "paymentTerm": 30,
  "orderReference": "test",
  "invoiceLines": [
    {
      "quantity": 1,
      "description": "Test",
      "sellingPrice": 10
    }
  ]
}

###

# @name getById
GET {{createdInvoiceLocation}}
Accept: application/json

###

# @name update
PUT {{createdInvoiceLocation}}
Content-Type: application/json

 {
    "customerId": "2d9d9aae-6c8c-447f-9861-08d9042c6bca",
    "invoiceDate": "2021-04-24T00:00:00",
    "paymentTerm": 31,
    "orderReference": "test 6",
    "invoiceLines": [
      {
        "quantity": 1,
        "description": "Test updated2",
        "sellingPrice": 10.00,
        "id": "8a45a01e-dcff-45ce-545e-08d90f8b7256"
      },
      {
        "quantity": 2,
        "description": "Line 2",
        "sellingPrice": 10.00,
        "id": "7d9e398d-5046-46fd-545f-08d90f8b7256"
      }
    ],
    "id": "c2e085af-7218-4b4f-7caa-08d90f2dd32a",
    "timestamp": "AAAAAAABX5I="
  }

###

# @name copy
POST {{createdInvoiceLocation}}/copy
Content-Type: application/json

{
}

###

# @name getCopyById
GET {{copyInvoiceLocation}}
Accept: application/json

###

# @name auditlog
GET {{createdInvoiceLocation}}/auditlog
  ?pageIndex=0
  &pageSize=10
Accept: application/json

###

# @name delete
DELETE {{createdInvoiceLocation}}
Content-Type: application/json

{
}

###